seed: 1
cutoff: 6.0

data:
  filename: data.pkl.gz
  test_filename: test.pkl.gz
  reference_energy: 0
  # save_dataset: False
  stress_units: eV/A3 # eV/A3 (default) or GPa or kbar or -kbar


potential:
   # If elements not provided - determined automatically from data
  preset: GRACE_1LAYER # LINEAR, FS, GRACE_1LAYER, GRACE_2LAYER

  ## For custom model from model.py::custom_model
  #  custom: model.custom_model

  # keywords-arguments that will be passed to preset or custom function
  kwargs: {lmax: 4, n_rad_max: 42, n_rad_base: 8, max_order: 4, n_mlp_dens: 16}

  #shift: False # True/False
  scale: True # False/True or float

fit:
  loss: {
    energy: { weight: 1.0, type: huber , delta: 1.00 },
    forces: { weight: 10.0, type: huber , delta: 1.00 },
    stress: { weight: 100.0, type: huber , delta: 1.00 },
    
  }

  maxiter: 2000 # Number of epochs / iterations

  optimizer: Adam
  opt_params: {
            learning_rate: 0.0001,
            amsgrad: True,
            use_ema: True,
            ema_momentum: 0.99,
            weight_decay: null,
            clipvalue: 1.0,
        }

  # for learning-rate reduction
  learning_rate_reduction: { patience: 10, factor: 0.98, min: 1.0e-7, stop_at_min: True, resume_lr: True, }

  #  optimizer: L-BFGS-B
  #  opt_params: { "maxcor": 100, "maxls": 20 }

  ## needed for low-energy tier metrics and for "convex_hull"-based distance of energy-based weighting scheme
  compute_convex_hull: False
  batch_size: 8 # Important hyperparameter for Adam and irrelevant (but must be) for L-BFGS-B
  test_batch_size: 16 # test batch size (optional)

  jit_compile: True
#  eval_init_stats: True # to evaluate initial metrics

  train_max_n_buckets: 256 # max number of buckets (group of batches of same shape) in train set
  test_max_n_buckets: 8 # same for test

  checkpoint_freq: 4 # frequency for **REGULAR** checkpoints.
  #save_all_regular_checkpoints: True # to store ALL regular checkpoints
  progressbar: True # show batch-evaluation progress bar
  train_shuffle: True # shuffle train batches on every epoch
